{% set name = "ordered_enum" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ordered_enum-{{ version }}.tar.gz
  sha256: a821dbbe2f998a1ef4c5974c8cd8bdb62e0ddb20ddcd0851b091538c7f944ba0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - flit-core >=3.2,<4
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - ordered_enum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/woodruffw/ordered_enum
  summary: A small library for adding total orderings to enums
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
