{% set name = "ordered_enum" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ordered_enum-{{ version }}.tar.gz
  sha256: c06595263d09dc31d60006d212692dccaf623125774efd84bc01f90d3cb71102

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6

test:
  imports:
    - ordered_enum
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/woodruffw/ordered_enum
  summary: A small library for adding total orderings to enums
  license: MIT
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - thewchan
